;;; Automatically generated by ‘recentf’ on Sun Dec 24 19:51:25 2023.

(setq recentf-list
      '(
        "~/org/20231224T175327--cheatsheet__cheatsheet.org"
        "~/org/20231224T181841--stuff-about-cpp__cpp.org"
        "~/.emacs.d/emacs-config.org"
        "~/org/20231224T181841--stuff-about-c__c.org"
        "~/org/20231224T181841--things-of-cpp.org"
        "~/org/20231224T181841--things-of-cpp__cpp.org"
        "~/org/20231224T180532--stl__cpp.org"
        "~/org/20231224T174029--emacs-cheatsheet__emacs.org"
        "~/org/20231104T145832--protobuf__studying.org"
        "~/void/test.el"
        "~/.emacs.d/init.el"
        "~/void/hello-elisp.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
