;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(denote--date-history consult--find-history denote--file-history denote--subdir-history consult-notes-history consult--grep-history org-link--history denote--keyword-history denote--title-history consult-imenu--history minibuffer-history org-read-date-history eww-prompt-history consult--line-history extended-command-history buffer-name-history consult-org--history empty-history file-name-history))
(setq denote--file-history '("~/org/20231224T180532--stl__cpp.org" "~/org/20231224T175327--cheatsheet__cheatsheet.org" "~/org/20231224T181841--stuff-about-cpp__cpp.org" "~/org/20231224T175327--cheatsheet__cheatsheet.org" "~/org/20231224T181841--stuff-about-cpp__cpp.org" "~/org/20231224T181841--things-of-cpp__cpp.org" "~/org/20231104T145832--protobuf__studying.org"))
(setq consult-notes-history '("20231224T181841--things-of-cpp__cpp.org�����" "20231224T175327--cheatsheet__cheatsheet.org�����" "20231224T174029--emacs-cheatsheet__emacs.org�����" "20231104T145832--protobuf__studying.org�����"))
(setq denote--keyword-history '("cpp" "c++" "cpp" "cheatsheet" "emacs" "studying"))
(setq denote--title-history '("Stuff about Cpp" "sdf" "Things of Cpp" "STL" "Cheatsheet" "emacs cheatsheet" "protobuf"))
(setq minibuffer-history '("C++中为什么要有allocator类？" "深入剖析STL内存分配器allocator及其萃取器" "STL Allocator 内存分配全揭秘" "remacs的世界" "Don't forward things that aren't forwarding references" "C++面试真题！如何实现一个类，在父类没有虚析构函数的情况下，通过父类指针析构子类对象？" "
wsl 更换存储位置" "安装WSL时，出现错误0x800701bc" "WSL2启动时提示：参考的对象类型不支持尝试的操作" "Ubuntu 22.04换国内源 清华源 阿里源 中科大源 163源" "Source code Pro" "Sarasa-Mono-SC-Nerd" "Sarasa Mono Sc Nerd" "magit" "consult-notes" "HEADER-ARGS" ":tangle init.el" "HEADER-ARGS" ":tangle init.el" "HEADER-ARGS"))
(setq eww-prompt-history '("www.baidu.com"))
(setq consult--line-history '("magit" "denote"))
(setq extended-command-history '("dired" "org-babel-tangle" "denote-rename-file" "denote-keywords-add" "denote-keywords-remove" "denote-keywords-add" "org-babel-tangle" "denote-keywords-add" "org-babel-tangle" "eshell" "dired" "eshell" "package-install" "package-refresh-contents" "emacs-version" "consult-imenu-multi" "consult-imenu" "eww" "shell"))
(setq buffer-name-history '("test.el" "emacs-config.org"))
(setq consult-org--history '("pac" "dev " "init.el loading" "org" "consult notes" "org" "denote" "org" "org mode" "init-base" "loading" "edit" "consult" "init base"))
(setq file-name-history '("~/.bashrc" "~/bash/set_proxy" "~/org/" "~/org/20231224T181841--stuff-about-c__c.org" "~/void/test.el" "~/.emacs.d/init.el" "~/void/test.el" "~/void/" "~/void/hello-elisp.el" "~/.emacs.d/emacs-config.org" "~/.emacs.d/etc/yasnippet/snippets/org-mode/elisp-source" "~/.emacs.d/etc/yasnippet/snippets/org-mode" "~/.emacs.d/etc/yasnippet/snippets/" "~/.emacs.d/emacs-config.org"))
(setq mark-ring 'nil)
(setq search-ring 'nil)
(setq regexp-search-ring 'nil)
(setq extended-command-history '("dired" "org-babel-tangle" "denote-rename-file" "denote-keywords-add" "denote-keywords-remove" "denote-keywords-add" "org-babel-tangle" "denote-keywords-add" "org-babel-tangle" "eshell" "dired" "eshell" "package-install" "package-refresh-contents" "emacs-version" "consult-imenu-multi" "consult-imenu" "eww" "shell"))
